# Generated by Django 3.1.5 on 2021-01-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='id материала')),
                ('name', models.TextField(verbose_name='Название материала')),
                ('amount', models.TextField(verbose_name='кол-во собранного материала')),
            ],
            options={
                'verbose_name': 'Профиль',
            },
        ),
    ]
