# Generated by Django 3.1.5 on 2021-01-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Отчёт'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='external_id',
        ),
    ]
