# Generated by Django 3.1.5 on 2021-01-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_timetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
    ]
