# Generated by Django 3.1.5 on 2021-01-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_auto_20210128_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
    ]
